package com.sdm.phr.gui;

import com.sdm.phr.CryptoUtil;
import com.sdm.phr.DatabaseClient;
import com.sdm.phr.KeyConfig;
import com.sdm.phr.cpabe.Cpabe;
import java.io.File;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class AddUser extends javax.swing.JPanel {
    Main parent;
    Map<String, Integer> orgnMap = null;

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
    }
    
    public AddUser(Main parent) {
        initComponents();
        this.parent = parent;
    }

    public void updateOrgnList() {
        orgnMap = DatabaseClient.getInstance().getOrgnMap();
        Vector orgnNameVector = new Vector();
        for (String name : orgnMap.keySet()) {
            orgnNameVector.add(name);
        }
        final DefaultComboBoxModel model = new DefaultComboBoxModel(orgnNameVector);
        jOrgnCombo.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFullName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jOrgnCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAttributes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jbtnAddUser = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jAccessRightCombo = new javax.swing.JComboBox();

        jLabel1.setText("Name");

        jFullName.setText(" ");
        jFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFullNameFocusGained(evt);
            }
        });

        jLabel2.setText("Organization");

        jLabel3.setText("Attributes");

        jAttributes.setColumns(20);
        jAttributes.setRows(5);
        jScrollPane1.setViewportView(jAttributes);

        jLabel4.setText("<html>Separate attributes by space.<br> use underscore ('_') for multi-word attributes.<br> e.g type:doctor hospital:Hospital_A</html>");

        jbtnAddUser.setText("Add User");
        jbtnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddUserActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setText("Add a new user");

        jLabel6.setText("Keys to generate");

        jAccessRightCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Read Key", "Write Key", "Read and Write Key" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jFullName)
                                .addComponent(jOrgnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jAccessRightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOrgnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jAccessRightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAddUser)
                    .addComponent(jbtnCancel))
                .addGap(0, 25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddUserActionPerformed
        String fullName = jFullName.getText().trim();
        String orgnName = (String) jOrgnCombo.getSelectedItem();
        String attributes = jAttributes.getText().trim();
        int accessKeysChoice = jAccessRightCombo.getSelectedIndex();

        if (fullName.isEmpty() || orgnName.isEmpty() || attributes.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // create a secret key for user
        Cpabe phr = new Cpabe();
        String baseKeyDownloadPath = System.getProperty("user.home") + File.separator + "Desktop" + File.separator;
        String readKeyDownloadPath = baseKeyDownloadPath+fullName.replaceAll(" ", "_") + "_read.key";
        String writeKeyDownloadPath = baseKeyDownloadPath+fullName.replaceAll(" ", "_") + "_write.key";
        System.out.println("read key path:"+readKeyDownloadPath);

        try {
            System.out.println("choice:"+accessKeysChoice);
            switch (accessKeysChoice) {
                case 0:
                    phr.keygen(KeyConfig.getInstance().getPatientReadPublicKeyPath(), readKeyDownloadPath, KeyConfig.getInstance().getPatientReadMasterKeyPath(), attributes);
                    break;
                case 1:
                    phr.keygen(KeyConfig.getInstance().getPatientWritePublicKeyPath(), writeKeyDownloadPath, KeyConfig.getInstance().getPatientWriteMasterKeyPath(), attributes);
                    break;
                case 2:
                    phr.keygen(KeyConfig.getInstance().getPatientReadPublicKeyPath(), readKeyDownloadPath, KeyConfig.getInstance().getPatientReadMasterKeyPath(), attributes);
                    phr.keygen(KeyConfig.getInstance().getPatientWritePublicKeyPath(), writeKeyDownloadPath, KeyConfig.getInstance().getPatientWriteMasterKeyPath(), attributes);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "No such option available", "Error", JOptionPane.ERROR_MESSAGE);
                    return;

            }
            //update database
            String readSecretKeyChecksum = CryptoUtil.getFileChecksum(readKeyDownloadPath, "SHA1");
            String writeSecretKeyChecksum = CryptoUtil.getFileChecksum(writeKeyDownloadPath, "SHA1");
            int orgnId = orgnMap.get(orgnName);
            DatabaseClient.getInstance().addUser(fullName, orgnId, attributes, readSecretKeyChecksum,writeSecretKeyChecksum);
            JOptionPane.showMessageDialog(null, "User added successfully. Secret key(s) for user is created at following path:" + baseKeyDownloadPath);
            
            //clean up
            jFullName.setText("");
            jAttributes.setText("");

        } catch (Exception ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ops! Something went wrong.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtnAddUserActionPerformed

    private void jFullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFullNameFocusGained
         if(orgnMap==null){
            updateOrgnList();
        }
    }//GEN-LAST:event_jFullNameFocusGained

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        parent.nextPanel(Main.PATIENT_HOME);
    }//GEN-LAST:event_jbtnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jAccessRightCombo;
    private javax.swing.JTextArea jAttributes;
    private javax.swing.JTextField jFullName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox jOrgnCombo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAddUser;
    private javax.swing.JButton jbtnCancel;
    // End of variables declaration//GEN-END:variables
}
